[DO NOT MERGE] Test pull request
khou22/khou22.github.io pull request #36
Opened 2024-02-12 19:29 UTC by khou22

* This is a test PR for an experimental AI app

### Here is an image

![Screenshot 2024-02-12 at 11 28 57 AM](https://github.com/khou22/khou22.github.io/assets/6607077/7daf0156-2f4a-4375-adc9-2b6065f9e82a)

2024-02-16 15:51 UTC, khou22 commented on scripts/fib.py
> +def fib(n: int) -> int:
Add docstring

```suggestion
def fib(n: int) -> int:
    """
    Calculate the nth Fibonacci number.

    Args:
        n (int): The index of the Fibonacci number to calculate.

    Returns:
        int: The nth Fibonacci number.

    """
    if n == 0:
        return 0
    elif n == 1:
        return 1
    else:
        return fib(n - 1) + fib(n - 2)
```

[Suggestion by Codeium](https://codeium.com//khou22/khou22.github.io/36/review)

2024-02-16 15:52 UTC, khou22 commented on scripts/fib.py
> +        return fib(n - 1) + fib(n - 2)
Add docstring

```suggestion
def fib(n: int) -> int:
    """
    Calculate the nth Fibonacci number.

    Args:
        n (int): The index of the Fibonacci number to calculate.

    Returns:
        int: The nth Fibonacci number.

    """
    if n == 0:
        return 0
    elif n == 1:
        return 1
    else:
        return fib(n - 1) + fib(n - 2)
```

[Suggestion by Codeium](https://codeium.com//khou22/khou22.github.io/36/review)

2024-02-16 15:58 UTC, khou22 commented on scripts/fib.py
> +def fib(n: int) -> int:
Add a docstring for this

```suggestion
def fib(n: int) -> int:
    """Calculate the nth Fibonacci number."""
```

[Suggestion by Codeium](https://codeium.com//khou22/khou22.github.io/36/review)

2024-02-16 16:02 UTC, khou22 commented on scripts/fib.py
> +def fib(n: int) -> int:
Add a docstring to the function

```suggestion
def fib(n: int) -> int:
    """Calculate the Fibonacci number for a given integer n."""
    if n == 0:
        return 0
    elif n == 1:
        return 1
    else:
        return fib(n - 1) + fib(n - 2)
```

[Suggestion by Codeium](https://codeium.com//khou22/khou22.github.io/36/review)

2024-02-16 16:04 UTC, khou22 commented on scripts/fib.py
> +        return fib(n - 1) + fib(n - 2)
Add a docstring to the function

```suggestion
def fib(n: int) -> int:
    """Return the nth Fibonacci number."""
    if n == 0:
        return 0
    elif n == 1:
        return 1
    else:
        return fib(n - 1) + fib(n - 2)
```

[Suggestion by Codeium](https://codeium.com//khou22/khou22.github.io/36/review)

2024-02-16 16:06 UTC, khou22 commented on scripts/fib.py
> +        return fib(n - 1) + fib(n - 2)
Add a docstring to the function

```suggestion
def fib(n: int) -> int:
    """Calculate the nth Fibonacci number."""
    if n == 0:
        return 0
    elif n == 1:
        return 1
    else:
        return fib(n - 1) + fib(n - 2)
```

[Suggestion by Codeium](https://codeium.com//khou22/khou22.github.io/36/review)

2024-02-16 20:51 UTC, khou22 commented on scripts/fib.py
> +        return fib(n - 1) + fib(n - 2)
Add docstring

```suggestion
def fib(n: int) -> int:
    """
    Calculate the nth Fibonacci number.
    """
    if n == 0:
        return 0
    elif n == 1:
        return 1
    else:
        return fib(n - 1) + fib(n - 2)
```

[Suggestion by Codeium](https://codeium.com//khou22/khou22.github.io/36/review)

2024-02-16 21:00 UTC, khou22 commented on scripts/fib.py
> +        return fib(n - 1) + fib(n - 2)
Add docstring

```suggestion
def fib(n: int) -> int:
    """
    Calculate the nth Fibonacci number.

    Args:
        n (int): The position of the Fibonacci number to calculate.

    Returns:
        int: The nth Fibonacci number.

    """
    if n == 0:
        return 0
    elif n == 1:
        return 1
    else:
        return fib(n - 1) + fib(n - 2)
```

[Suggestion by Codeium](https://codeium.com//khou22/khou22.github.io/36/review)

2024-02-17 01:04 UTC, mraheja commented on README.md
> +
testing

```suggestion
The comment "t" does not provide any specific feedback or suggestions for improvement. Please provide more detailed comments or suggestions related to the code change.
```

[Suggestion by Codeium](https://codeium.com//khou22/khou22.github.io/36/review)

2024-02-17 02:41 UTC, mraheja commented on scripts/fib.py
> +        return fib(n - 1) + fib(n - 2)
add docstring

```suggestion
def fib(n: int) -> int:
    """
    Calculates the nth Fibonacci number.
    
    Returns:
        int: The nth Fibonacci number.
    """
    if n == 0:
        return 0
    elif n == 1:
        return 1
    else:
        return fib(n - 1) + fib(n - 2)
```

[Suggestion by Codeium](https://codeium.com//khou22/khou22.github.io/36/review)

2024-02-17 19:45 UTC, khou22 commented on README.md
>  [![built with Codeium](https://codeium.com/badges/main)](https://codeium.com?repo_name=khou22%2Fkhou22.github.io) [![streak](https://codeium.com/badges/v2/user/kevin/streak)](https://codeium.com/prof
Consider adding alt text to the images for accessibility purposes

2024-02-20 18:24 UTC, khou22 commented on scripts/fib.py
> +        return fib(n - 1) + fib(n - 2)
Add a docstring to the function

```suggestion
def fib(n: int) -> int:
    """Calculate the nth Fibonacci number using recursive approach. Returns int."""
    if n == 0:
        return 0
    elif n == 1:
        return 1
    else:
        return fib(n - 1) + fib(n - 2)
```

[Suggestion by Codeium](https://codeium.com//khou22/khou22.github.io/36/review)

2024-02-20 18:27 UTC, khou22 commented on scripts/fib.py
> +        return fib(n - 1) + fib(n - 2)
Add a docstring to the function fib

```suggestion
def fib(n: int) -> int:
    """Calculate the nth Fibonacci number."""
    if n == 0:
        return 0
    elif n == 1:
        return 1
    else:
        return fib(n - 1) + fib(n - 2)
```

[Suggestion by Codeium](https://codeium.com//khou22/khou22.github.io/36/review)

2024-02-20 22:26 UTC, khou22 commented on scripts/fib.py
> +        return fib(n - 1) + fib(n - 2)
Add a docstring to the function

```suggestion
def fib(n: int) -> int:
    """Calculate the nth Fibonacci number. Returns 0 if n < 0."""
    if n == 0:
        return 0
    elif n == 1:
        return 1
    else:
        return fib(n - 1) + fib(n - 2)
```

[Suggestion by Codeium](https://codeium.com//khou22/khou22.github.io/36/review)

2024-02-21 02:52 UTC, mraheja commented on scripts/fib.py
> +def fib(n: int) -> int:
test

2024-02-21 05:54 UTC, mraheja reviewed
test

2024-02-21 05:54 UTC, mraheja commented on scripts/fib.py
> +        return fib(n - 1) + fib(n - 2)
add docstring

```suggestion
def fib(n: int) -> int:
    """
    Calculate the Fibonacci number for a given input n.

    Args:
        n (int): The input number for which the Fibonacci number is to be calculated.

    Returns:
        int: The Fibonacci number corresponding to the input n.
    """
    if n == 0:
        return 0
    elif n == 1:
        return 1
    else:
        return fib(n - 1) + fib(n - 2)
```

[Suggestion by Codeium](https://codeium.com//khou22/khou22.github.io/36/review)

2024-02-21 06:43 UTC, mraheja commented on README.md
hello

2024-02-21 06:47 UTC, mraheja commented on README.md
hi

2024-02-21 06:50 UTC, mraheja commented on scripts/fib.py
hello

2024-02-21 06:55 UTC, mraheja commented on README.md
hi

2024-02-21 06:55 UTC, mraheja commented on README.md
test2

2024-02-21 21:02 UTC, mraheja commented on README.md
![cats](https://media4.giphy.com/media/3o72EX5QZ9N9d51dqo/giphy.gif?cid=9f0f6425m55y0ej53894z4bsiv5vkbgpkigx56mivbj0k6wu&ep=v1_gifs_search&rid=giphy.gif&ct=g)

2024-02-22 00:45 UTC, mraheja commented on README.md
> +This change should not be checked in!
test

2024-02-22 22:49 UTC, mraheja requested changes
bruh moment

2024-02-22 22:49 UTC, mraheja approved these changes
bruh moment

2024-02-22 22:50 UTC, mraheja approved these changes
d

2024-02-22 23:24 UTC, mraheja commented on scripts/fib.py
> +        return 1
test comment

2024-02-22 23:25 UTC, mraheja commented on scripts/fib.py
> +        return 0
test

2024-02-23 20:47 UTC, mraheja reviewed
d

2024-02-23 20:47 UTC, mraheja reviewed
d

2024-02-23 20:50 UTC, mraheja reviewed
d

2024-02-23 20:50 UTC, mraheja reviewed
l

2024-02-23 20:51 UTC, mraheja reviewed
l

2024-02-23 20:52 UTC, mraheja approved these changes
ld

2024-02-23 20:52 UTC, mraheja approved these changes
ld

2024-02-23 20:58 UTC, mraheja approved these changes
good morning

2024-02-23 20:59 UTC, mraheja requested changes
good morning

2024-02-23 21:14 UTC, mraheja approved these changes
approved

2024-02-23 21:46 UTC, mraheja approved these changes

2024-02-23 21:46 UTC, mraheja approved these changes
nice

2024-02-23 21:51 UTC, mraheja approved these changes
huge1

2024-02-23 21:52 UTC, mraheja approved these changes
d

2024-02-23 21:52 UTC, mraheja commented on README.md
> +This change should not be checked in!
pending1

```suggestion
This change should not be checked in!
```

2024-02-23 21:53 UTC, mraheja approved these changes
something working

2024-02-23 21:53 UTC, mraheja commented on README.md
> +This change should not be checked in!
pending1

```suggestion
This change should not be checked in!
```

2024-02-23 21:53 UTC, mraheja commented on scripts/fib.py
> +    print(fib(10))
testing

```suggestion
def fib(n: int) -> int:
    if n <= 1:
        return n
    return fib(n - 1) + fib(n - 2)

def main() -> None:
    print(fib(10))
```

2024-02-23 21:58 UTC, mraheja approved these changes
testing submit

2024-02-23 21:58 UTC, mraheja commented on scripts/fib.py
> +        return fib(n - 1) + fib(n - 2)
testing2

```suggestion
        return fib(n - 1) + fib(n - 2)
```

2024-02-23 21:58 UTC, mraheja commented on README.md
> +
test3

2024-03-08 19:03 UTC, khou22 commented
Closing test PR

2024-03-08 19:03 UTC, closed without merging